[project]
name = "03-textattack"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = "~=3.10.0"
dependencies = [
    "ipykernel>=6.30.1",
    "tensorflow~=2.10.0",
    "textattack[optional,tensorflow]>=0.3.10",
    "transformers~=4.30.0",
    "numpy~=1.24.0",
]
