stages:
  - build
  - deploy

variables:
  UV_VERSION: "0.5"
  PYTHON_VERSION: "3.12"
  BASE_LAYER: bookworm-slim
  # GitLab CI creates a separate mountpoint for the build directory,
  # so we need to copy instead of using hard links.
  UV_LINK_MODE: copy
  UV_CACHE_DIR: .uv-cache

# Only run pipeline on main branch
workflow:
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'


# checks:
#   stage: checks
#   image: ghcr.io/astral-sh/uv:$UV_VERSION-python$PYTHON_VERSION-$BASE_LAYER
#   cache:
#     - key:
#         files:
#           - uv.lock
#       paths:
#         - $UV_CACHE_DIR
#   script:
#     - uv sync
#     - uv run ruff check .
#     - uv run ruff format --check .
#     - uv cache prune --ci

# Build MkDocs site
build_mkdocs:
  stage: build
  image: ghcr.io/astral-sh/uv:$UV_VERSION-python$PYTHON_VERSION-$BASE_LAYER
  cache:
    - key:
        files:
          - doc/uv.lock
      paths:
        - $UV_CACHE_DIR
  script:
    - cd doc
    - uv sync
    - uv run mkdocs build -d site
    - uv cache prune --ci
  artifacts:
    paths:
      - doc/site
    expire_in: 1 week

# Deploy production (main branch only)
deploy_production:
  stage: deploy
  dependencies:
    - build_mkdocs
  image: nginx:latest
  script:
    # Copy the built MkDocs site into Nginx default html folder
    - mkdir -p /usr/share/nginx/html
    - cp -r doc/site/* /usr/share/nginx/html/
    # Start Nginx in the foreground
    - nginx -g 'daemon off;' &
    - sleep 2
    - echo "MkDocs site is now running via Nginx"
  artifacts:
    paths:
      - doc/site
  environment:
    name: production
    url: ${CI_PROJECT_URL}/-/environments/production