[project]
name = "course-ai-security"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "mkdocs-awesome-nav>=3.2.0",
    "mkdocs-material>=9.6.20",
]
